# Generated by Django 2.2 on 2019-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(default='PLN', max_length=50)),
                ('place', models.CharField(default='place', max_length=100)),
                ('img_link', models.TextField(max_length=500)),
                ('title', models.CharField(default='title', max_length=200)),
                ('title2', models.TextField(blank=True, null=True)),
                ('address', models.TextField(default='address')),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_cont', models.TextField(blank=True, null=True)),
                ('promo_dates', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
