# Generated by Django 2.2 on 2019-04-17 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
